---
title: "Lab1"
author: "Jaime Uribe, Juan Pablo Duque, Soranyi Toncel, Valentina Zapata"
date: "2024-07-25"
output: html_document
---

```{r}
#Cargar el archivo y asignar el nombre datos
BaseLaboratorio1 <- read.csv("C:/Users/clase/Downloads/BaseLaboratorio1.csv")
datos<-BaseLaboratorio1
```
```{r}
#Imprimir las primeros 6 filas
head (datos)
```

```{r}
#Explorar variables que conforman a datos con la función str
str (datos)
```
#La unica variable categórica es la denominana Country. Las demas son cuantitativas. La variable country es nominal y en el caso de las cuantitativas, el año es la unica discreta, las demas son continuas.
```{r}
install.packages ("summarytools")
```

```{r}
library (summarytools)

```
```{r}
# Distribución de frecuencias individuales
freq(datos$Year)
```
```{r}
freq(datos$Country)
```
#Graficos
```{r}
library(tidyverse)
```
```{r}
library (ggplot2)
ggplot(datos, aes(x=Year, fill=Country))+
geom_bar (width = 1)+coord_polar("y")
```
#Distribución de variables produccion anual de energia solar, eolica e hidraulica
```{r}
par (mfrow=c(1,3))
hist(datos$SolarEnergy,main="Solar__energy")
grid()
hist(datos$WindEnergy,main="Wind__energy")
grid()
hist(datos$HydroEnergy,main="Hydro__energy")
grid()

```
```{r}

paisesyEnergias <- datos[2:5]
data_long <- paisesyEnergias %>%
  pivot_longer(
    cols = c(SolarEnergy, WindEnergy, HydroEnergy),
    names_to = "EnergyType",
    values_to = "Value"
  )

# Crear el gráfico
ggplot(data_long, aes(x = Country, y = Value, fill = EnergyType)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(
    title = "Promedio de Energía por Tipo y País",
    x = "País",
    y = "Promedio de Energía en GWh",
    fill = "Tipo de Energía"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


```{r}
library(tidyverse)
library(ggplot2)

ggplot(datos, aes(x = SolarEnergy, color = Country)) +
  geom_histogram(fill = "white", alpha = 0.5, position = "identity") +
  theme_bw() +
  xlab("Energía Solar") +
  ylab("Frecuencia")
```
```{r}




primerCuantitativas <- datos[1]
segundaCuantitativas <- datos[3:7]
totalCuantitativas<-cbind(primerCuantitativas,segundaCuantitativas)
print(totalCuantitativas)




penult <-totalCuantitativas[2:4]
promedios <- colMeans(penult)

# Convertir los promedios a un data frame para graficar
df_promedios <- data.frame(
  TipoDeEnergia = names(promedios),
  Promedio = promedios
)

# Crear la gráfica de barras
ggplot(df_promedios, aes(x = TipoDeEnergia, y = Promedio, fill = TipoDeEnergia)) +
  geom_bar(stat = "identity") +
  labs(title = "Promedio de Energías",
       x = "Tipo de Energía",
       y = "Promedio en GWh",
       fill = "Tipo de Energía") +
  theme_minimal()
```


